name: CICD with CodeQL Pipeline

on:
  push:
    branches:
      - main # trigger when pushes are made to main branch

jobs:
  codeql-analysis:
    name: Analyze Code with CodeQL
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ['python']

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up codeql
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Code Analysis
        uses: github/codeql-action/analyze@v2

  build-and-deploy:
    name: Build and Deploy Application
    runs-on: ubuntu-latest
    needs: codeql-analysis

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: | 
          
          pip install -r webapp/requirements.txt

      - name: Run tests with coverage
        run: | 
            pytest --cov=webapp tests/
          
      - name: Stop and remove old containers
        run: | 
          docker rm -f assessment-web-app || true

      - name: Build Docker Image
        run: |
          docker build -t assessment-web-app:latest .

      - name: Run Container
        run: |
          docker run -d -p 3000:3000 --name assessment-web-app assessment-web-app:latest

      - name: Check if Container is Running
        run: bash monitor.sh
        shell: bash

      - name: Wait for App to start up
        run: sleep 20

      - name: Access Application
        run: |
          curl --fail http://localhost:3000 || exit 1